"use client";

import { useEffect, useRef } from "react";
import Link from "next/link";
import Icon from "@/components/ui/Icon/Icon";
import CountUp from "@/components/ui/CountUp/CountUp";
import styles from "./Hero.module.css";

const nodes=[[1010,110],[1170,205],[1330,96],[1262,372],[1398,520],[1110,640],[150,620],[60,452],[330,760],[660,70]];
const links=[[0,1],[1,2],[1,3],[3,4],[3,5],[6,7],[6,8],[0,9]];
const particles=[{x:6,y:30,d:0,t:11},{x:18,y:72,d:-3,t:13},{x:31,y:18,d:-6,t:12},{x:44,y:84,d:-2,t:14},{x:57,y:12,d:-8,t:10},{x:66,y:64,d:-5,t:12},{x:78,y:26,d:-1,t:13},{x:88,y:78,d:-7,t:11},{x:94,y:42,d:-4,t:15},{x:50,y:50,d:-9,t:16}];

export default function Hero(){
 const heroRef=useRef(null);
 useEffect(()=>{const hero=heroRef.current;if(!hero||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const pointer=matchMedia("(hover: hover) and (pointer: fine) and (min-width: 1024px)"),scrollQuery=matchMedia("(min-width: 768px)"),target={x:0,y:0},current={x:0,y:0};let width=hero.offsetWidth,height=hero.offsetHeight,lastScroll=-1,frame=0;const render=()=>{frame=0;current.x+=(target.x-current.x)*.08;current.y+=(target.y-current.y)*.08;hero.style.setProperty("--px",current.x.toFixed(4));hero.style.setProperty("--py",current.y.toFixed(4));hero.style.setProperty("--gx",`${(((current.x+1)/2)*width).toFixed(1)}px`);hero.style.setProperty("--gy",`${(((current.y+1)/2)*height).toFixed(1)}px`);const scroll=scrollQuery.matches?Math.min(Math.max(scrollY,0),height):0;if(scroll!==lastScroll){hero.style.setProperty("--sy",scroll.toFixed(1));lastScroll=scroll}if(Math.abs(target.x-current.x)>.0005||Math.abs(target.y-current.y)>.0005)frame=requestAnimationFrame(render)};const request=()=>{if(!frame)frame=requestAnimationFrame(render)};const move=e=>{if(!pointer.matches)return;const r=hero.getBoundingClientRect();target.x=((e.clientX-r.left)/r.width)*2-1;target.y=((e.clientY-r.top)/r.height)*2-1;hero.dataset.pointer="on";request()};const leave=()=>{target.x=0;target.y=0;hero.dataset.pointer="off";request()};const resize=()=>{width=hero.offsetWidth;height=hero.offsetHeight;if(!pointer.matches)leave();lastScroll=-1;request()};hero.addEventListener("pointermove",move,{passive:true});hero.addEventListener("pointerleave",leave);addEventListener("scroll",request,{passive:true});addEventListener("resize",resize);request();return()=>{hero.removeEventListener("pointermove",move);hero.removeEventListener("pointerleave",leave);removeEventListener("scroll",request);removeEventListener("resize",resize);cancelAnimationFrame(frame)}},[]);
 return <section ref={heroRef} className={styles.hero}>
  <div className={styles.bg} aria-hidden="true"><div className={styles.gridLayer}/><div className={styles.mesh}><span/><span/><span/></div><div className={styles.pointerGlow}/><svg className={styles.network} viewBox="0 0 1440 800" preserveAspectRatio="xMidYMid slice">{links.map(([a,b])=><line key={`${a}-${b}`} className={styles.link} x1={nodes[a][0]} y1={nodes[a][1]} x2={nodes[b][0]} y2={nodes[b][1]}/>)}{nodes.map(([x,y],i)=><g key={`${x}-${y}`}><circle className={styles.nodeHalo} cx={x} cy={y} r="11" style={{animationDelay:`${i*-.7}s`}}/><circle className={styles.node} cx={x} cy={y} r="3"/></g>)}</svg><div className={styles.radar}><span/><span/><span/><i className={styles.sweep}/></div><div className={styles.ghost}><div className={styles.ghostBar}><i/><i/><i/><b/></div><div className={styles.ghostBody}><div className={styles.ghostBeam}/></div></div>{particles.map(p=><span key={`${p.x}-${p.y}`} className={styles.particle} style={{left:`${p.x}%`,top:`${p.y}%`,animationDelay:`${p.d}s`,animationDuration:`${p.t}s`}}/>)}</div>
  <div className={`container ${styles.inner}`}>
   <div className={styles.copy}><span className={styles.badge}><i className={styles.liveDot}/>Complete website QA</span><h1>See What Your Website Is <span>Really Missing.</span></h1><p>We manually review your website page by page and section by section—checking design, layout, mobile responsiveness, images, content, usability, functionality and conversion issues.</p><div className={styles.actions}><Link className="btnSecondary" href="/free-report">Get Your Free Website Report<span className="btnIcon"><Icon name="arrowRight"/></span></Link><Link className={`btnGhost ${styles.howBtn}`} href="/how-it-works"><span className={styles.playIcon}><Icon name="play"/></span>See What We Check</Link></div><ul className={styles.assurances}><li><Icon name="check"/>Complete website QA</li><li><Icon name="check"/>Manual expert review</li><li><Icon name="check"/>Prioritized by impact</li></ul></div>
   <div className={styles.visualWrap} aria-label="Animated complete website QA preview"><div className={styles.visualTilt}><div className={styles.orbA}/><div className={styles.orbB}/><div className={styles.browser}><div className={styles.browserTop}><i/><i/><i/><span>yourwebsite.com</span><em className={styles.scanStatus}><Icon name="scan"/>QA in progress</em></div><div className={styles.scanArea}><div className={styles.fakeNav}/><div className={styles.fakeHero}><div><b/><b/><b/></div><div className={styles.previewCard}/></div><div className={styles.fakeCards}><i/><i/><i/></div><span className={`${styles.hit} ${styles.hitNav}`}><em>Header <Icon name="check"/></em></span><span className={`${styles.hit} ${styles.hitHero}`}><em>Layout <Icon name="check"/></em></span><span className={`${styles.hit} ${styles.hitCards}`}><em>Responsive <Icon name="check"/></em></span><div className={styles.scanTrack}><div className={styles.scanBeam}/></div></div></div><div className={`${styles.floatCard} ${styles.cardScore}`}><span>QA checks passed</span><strong><CountUp end={86} duration={1800} delay={400}/></strong><small>Strong foundation</small><i className={styles.meter}><b/></i></div><div className={`${styles.floatCard} ${styles.cardSeo}`}><span>Functionality</span><strong>Issues documented</strong></div><div className={styles.cursorPulse}><Icon name="arrowUpRight"/></div></div></div>
  </div>
 </section>
}
