"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import Icon from "@/components/ui/Icon/Icon";
import styles from "./Process.module.css";

const steps=[
 ["01","Share Your Website","Submit your website URL and tell us a little about your business, goals, and the areas you already feel need attention.","submit"],
 ["02","We QA the Full Website","We review pages, sections, design, responsiveness, content presentation, images, forms, navigation and functionality.","scan"],
 ["03","We Document the Issues","We organize every finding by page, section, severity and impact so the report stays useful.","priority"],
 ["04","You Receive the Report","You get screenshots, clear issue descriptions and recommended improvements for every important finding.","report"],
 ["05","We Can Help Improve It","If required, we can redesign or implement the recommended fixes.","compare"]];
const Bar=()=> <div className={styles.bar}><i/><i/><i/><span>signalreach.co</span></div>;
function Visual({type}){
 if(type==="submit") return <div className={`${styles.visual} ${styles.submit}`}><Bar/><div className={styles.submitBody}><small>Website URL</small><div className={styles.url}><span>https://example.com</span><button>Submit<i/></button></div><div className={styles.status}><b>✓</b><span><strong>Website received</strong><small>Preparing review...</small></span></div></div></div>;
 if(type==="scan") return <div className={`${styles.visual} ${styles.scanner}`}><Bar/><div className={styles.scanBody}><div className={styles.page}><b/><strong><i/><i/></strong><em><i/><i/><i/></em><span/></div><div className={styles.signals}>{["Design","Layout","Mobile","Images","Forms","Function"].map((x,i)=><b key={x} style={{"--d":`${i*.3}s`}}><i>✓</i>{x}</b>)}</div></div></div>;
 if(type==="priority") return <div className={`${styles.visual} ${styles.priority}`}><header><b>Documented findings</b><span>By page and section</span></header>{[["CRITICAL · MOBILE","Button overlaps content"],["HIGH · HEADER","Navigation breaks on tablet"],["MEDIUM · HERO","Image crop feels unbalanced"],["LOW · FORM","Confirmation text unclear"]].map((x,i)=><div className={styles.finding} key={x[1]} style={{"--d":`${i*.14}s`}}><small>{x[0]}</small><b>{x[1]}</b><i>0{i+1}</i></div>)}</div>;
 if(type==="report") return <div className={`${styles.visual} ${styles.report}`}><div className={styles.sheet}><header><b>SignalReach</b><span>Website QA Report</span></header><div className={styles.score}><b>24</b><small>Documented issues</small><i><em/></i></div><div className={styles.metrics}>{[["Design",86],["Function",74],["Content",79],["Mobile",91]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><i><em style={{width:`${x[1]}%`}}/></i></div>)}</div><footer><span>Screenshots</span><span>Recommended Actions</span></footer></div></div>;
 return <div className={`${styles.visual} ${styles.compare}`}><header><span>Current website</span><span>Improved prototype</span></header><div className={styles.frame}><div className={styles.before}><i/><b/><span/><span/></div><div className={styles.after}><i/><b/><span/><span/><em/></div><div className={styles.slider}><b>↔</b></div></div></div>;
}
/* line segments stop GAP px short of each circle; a marker activates the moment the head reaches its segment end */
const GAP=8;
export default function Process(){
 const ref=useRef(null),[shown,setShown]=useState(-1),[reached,setReached]=useState(-1),[segs,setSegs]=useState([]);
 useEffect(()=>{const root=ref.current,items=[...root.querySelectorAll("[data-step]")];const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setShown(+e.target.dataset.step)),{rootMargin:"-36% 0px -36%"});items.forEach(x=>io.observe(x));const track=root.querySelector("[data-track]"),markers=[...root.querySelectorAll("[data-marker]")],check=root.querySelector("[data-check]");const update=()=>{const t=track.getBoundingClientRect().top,head=innerHeight*.5,pts=markers.map(m=>m.getBoundingClientRect()),c=check.getBoundingClientRect(),axis=pts[0].left+pts[0].width/2;/* the completion check joins the line only when it sits on the same axis (desktop) */if(Math.abs(c.left+c.width/2-axis)<4)pts.push(c);let hit=-1;pts.forEach((r,i)=>{if(head>=r.top-GAP)hit=i});setReached(hit);setSegs(pts.slice(1).map((r,i)=>{const top=pts[i].bottom+GAP,end=r.top-GAP,h=Math.max(0,end-top);return{top:top-t,h,fill:h?Math.max(0,Math.min(1,(head-top)/h)):0}}))};update();addEventListener("scroll",update,{passive:true});addEventListener("resize",update);return()=>{io.disconnect();removeEventListener("scroll",update);removeEventListener("resize",update)}},[]);
 return <section ref={ref} className={styles.section}><div className={styles.grid}/><div className={`container ${styles.intro}`}><span className="eyebrow">How it works</span><h2>From Your Website URL to a Clear Action Plan.</h2><p>A simple process designed to uncover what is holding your website back and show you exactly what to improve next.</p></div><div className={`container ${styles.timeline}`} data-track><div className={styles.line} aria-hidden="true">{segs.map((g,i)=><div key={i} className={styles.seg} style={{top:g.top,height:g.h}}><span data-moving={g.fill>0&&g.fill<1||undefined} style={{height:`${g.fill*100}%`}}/></div>)}</div>{steps.map((s,i)=>{const state=i<reached?"complete":i===reached?"active":"inactive";return <article key={s[0]} data-step={i} data-state={state} data-shown={i<=shown||undefined} className={`${styles.step} ${i%2?styles.even:styles.odd}`}><div className={styles.marker} data-marker>{state==="inactive"?<span>{s[0]}</span>:<span key="tick" className={styles.tick}>✓</span>}</div><div className={styles.copy}><small>Step {s[0]}</small><h3>{s[1]}</h3><p>{s[2]}</p></div><div className={styles.visualWrap}><Visual type={s[3]}/></div></article>})}</div><div className={styles.complete} data-step="5"><div className={styles.check} data-check data-on={reached>=steps.length||undefined}>✓</div><small>Your website roadmap is ready</small><h2>Now You Know Exactly What To Improve.</h2><p>You now have a clear picture of what is working, what needs attention, and the actions that can move your website forward.</p><div><Link className="btnPrimary" href="/free-report">Get Your Free Report <span className="btnIcon"><Icon name="arrowRight"/></span></Link><Link className={`btnGhost ${styles.secondary}`} href="/free-report">Book a Consultation</Link></div></div></section>
}
